### ISSUE TITLE
Colorer les noeuds en fonction du score obtenu

### ISSUE THREAD

**Issue by StephMathis** [StephMathis/mychess-openings#2]

**Comment by AIstanbul** [comment]
For review plz ;)

**Comment by StephMathis** [comment]
je n'ai pas vu les couleurs. C'est dans develop ?

**Comment by AIstanbul** [comment]
Dans main, je fais comme toi:)

**Comment by AIstanbul** [comment]
je viens de revérifier , je crois que tu as supprimé mes évols quand tu as pushé hier après moi (tu as du mal mergé) du coup je les remets

**Comment by AIstanbul** [comment]
@StephMathis : j'ai repush, pas sympa d'avoir écrasé mon code :)

**Comment by StephMathis** [comment]
merci, c'est sympa

**Comment by AIstanbul** [comment]
@StephMathis : is it better now?
